djangoProject2/blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'
urlpatterns = [
    #post views
    #path('',post_list, name='post_list'), #FBV
    path('<int:post_id>/share/',post_share,name='post_share'),
    path('', PostListView.as_view(), name='post_list'),  # CBV

    #path('<int:year>/<int:month>/<int:day>/<slug:post>/',post_detail,name='post_detail'),
    path('<int:id>/', post_detail, name='post_detail')

]

djangoProject2/djangoProject2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import *
from demo.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls',namespace='blog')),


]

djangoProject2/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Post (models.Model):
    STATUS_CHOICES = {
        ('draft','Draft'),
        ('published', 'Published'),
    }
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    body= models.TextField()
    publish= models.DateTimeField(default=timezone.now)
    created= models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    status= models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')

    def get_absolute_url(self):
        # return reverse('blog:post_detail',
        #                args=[self.publish.year,
        #                      self.publish.month,
        #                      self.publish.day,
        #                      self.slug])

        return reverse('blog:post_detail',
                       args=[self.id])

    class Meta:
        ordering=('-publish',)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

djangoProject2/blog/forms.py
from django import forms
from .models import *

class EmailPostForm(forms.Form):
    name= forms.CharField(max_length=25)
    email= forms.EmailField()
    to=forms.EmailField()
    comments=forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=('name','email','body')

djangoProject2/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from .forms import *
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from django.views.generic import ListView,DetailView
from django.core.mail import send_mail
# Create your views here.

def post_list(request):
    obj = Post.objects.all()
    paginator= Paginator(obj,3) #3 posts per page
    page=request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        #If the page is not an integer, deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        #If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,'blog/post/list.html',{'page': page,'posts': posts})

# def post_detail(request, year, month, day, post):
#     post = get_object_or_404(Post, slug=post,
#                             status='published',
#                             publish__year= year,
#                             publish__month= month,
#                             publish__day= day
#                             )
#
#
#     return render(request,'blog/post/detail.html',{'post':post})


def post_detail(request, id):
    post = get_object_or_404(Post, id=id)
    comments=post.comments.filter(active=True)
    new_comment=None

    if request.method =="POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment= comment_form.save(commit=False) #don't save in database yet
            new_comment.post=post #assign the current post to the comment
            new_comment.save() #save comment in the database
    else:
        comment_form= CommentForm()

    context = {
        'post': post,
        'comments':comments,
        'new_comment':new_comment,
        'comment_form':comment_form
    }

    return render(request, 'blog/post/detail.html', context)

def post_share(request, post_id):
    #retreive post by id
    post = get_object_or_404(Post, id=post_id)
    sent = False
    if request.method == "POST":
        #Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            #passed validations
            cd=form.cleaned_data
            #send email
            post_url= request.build_absolute_uri(post.get_absolute_url())
            subject= f"{cd['name']} recommends you read " f"{post.title}"
            message= f"Read {post.title} at {post_url}\n\n" f"cd['name']\'s comments: {cd['comments']}"
            send_mail(subject,message,'youssef12aly@gmail.com',[cd['to']])
    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', {'post':post, 'form':form})



# Class based views
class PostListView(ListView):
    queryset = Post.objects.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

djangoProject2/demo/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
# Create your views here.

def post_list(request):
    posts = Post.objects.all()

djangoProject2/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
<div id="sidebar">
    <h2>My blog</h2>
    <p>This is my blog.</p>

</div>
</body>
</html>

djangoProject2/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
 <h1>{{ post.title }}</h1>
 <p class="date">
    Published {{ post.publish }} by {{ post.author }}
 </p>
 {{ post.body|linebreaks }}
    {% with comments.count as total_comments %}
         <h2>
         {{ total_comments }} Comment{{ total_comments|pluralize }}
         </h2>
    {% endwith %}
    {% for comment in comments %}
         <div class="comment">
             <p class="info">
             Comment {{ forloop.counter }} by {{ comment.name }}
             {{ comment.created }}
             </p>
            {{ comment.body|linebreaks }}
         </div>
        {% empty %}
         <p>There are no comments yet.</p>
    {% endfor %}
    {% if new_comment %}
         <h2>Your comment has been added.</h2>
    {% else %}
         <h2>Add a new comment</h2>
         <form method="post">
             {{ comment_form.as_p }}
             {% csrf_token %}
             <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}
    <p>
         <a href="{% url "blog:post_share" post.id %}">
         Share this post
         </a>
    </p>
{% endblock %}

djangoProject2/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
 <h1>My Blog</h1>
 {% for post in posts %}
 <h2>
 <a href="{{ post.get_absolute_url }}">
 {{ post.title }}
 </a>
 </h2>
 <p class="date">
 Published {{ post.publish }} by {{ post.author }}
 </p>
 {{ post.body|truncatewords:30|linebreaks }}
 {% endfor %}
    {# {% include "pagination.html" with page=posts %} FBV #}
    {% include "pagination.html" with page=page_obj %} {# CBV #}

{% endblock %}

djangoProject2/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
 {% if sent %}
 <h1>E-mail successfully sent</h1>
 <p>
 "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
 </p>
 {% else %}
 <h1>Share "{{ post.title }}" by e-mail</h1>
 <form method="post">
 {{ form.as_p }}
 {% csrf_token %}
 <input type="submit" value="Send e-mail">
 </form>
 {% endif %}
{% endblock %}